### ISSUE TITLE
Can you make Logseq links from diagrams?

### ISSUE THREAD

**Issue by astubbs** [npgrosser/logseq-diagrams-as-code#14]
e.g. say you have a page [[person]], can you like to [[person]] from inside any of the diorama types? I guess not as the diagrams are rendered totally externally by the webervice.

**Comment by npgrosser** [comment]
Some diagram types do support URLs, but I am not aware of any URL you could create (regardless of it is inside the diagram or not), that would redirect you to another Logseq page.
Since Logseq is basically a web application, this could theoretically be possible, but currently, I do not know of any way to do that.
But that ultimately doesn't have much to do with the plugin itself.

**Comment by ayykamp** [comment]
Logseq does actually have its own URL scheme, just click top right on the "..." and then "copy page URL"
