### ISSUE TITLE
Mermaid Gantt doesnt scale with page width

### ISSUE THREAD

**Issue by statixVFX** [npgrosser/logseq-diagrams-as-code#6]
Hi,

When using logseq 0.7.5 and Diagrams as Code 0.0.13 and using standard mermaid syntax like
`gantt
    title A Gantt Diagram
    dateFormat  YYYY-MM-DD
    section Section
    A task           :a1, 2014-01-01, 30d
    Another task     :after a1  , 200d
    section Another
    Task in sec      :2014-01-12  , 12d
    another task      : 24d`

It doesnt scale with the page width, its always to narrow for anything meaningful to be used in a timeline. 
<img width="1150" alt="Screenshot 2022-07-09 at 16 32 03" src="https://user-images.githubusercontent.com/5736513/178110243-d6754065-ed04-44c0-8005-f6aaf83149ff.png">

**Comment by npgrosser** [comment]
_(Sry for the late reply)_

Due to the way the Logseq plugin API allows things to be rendered in a block, I'm not sure if this is even possible. Custom rendered content and the rest of the HTML document are relatively well isolated.

I'll take a closer look at this at some point. But at the moment, it's not super high on my priority list.
Nonetheless, if anyone has an idea or knows of a Logseq plugin that does exactly that (using the full width of the block to render custom content), please let me know.
